name: entmatcher
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - faiss-gpu=1.7.1
  - fml=0.1.0
  - keras=2.6.0
  - numpy=1.19.2
  - pip=23.3.1
  - python=3.8.10
  - pytorch=1.7.1
  - pip:
      - scipy==1.7.0
      - tensorflow-gpu==2.6.0
      - tqdm==4.66.2